### ISSUE TITLE
Plans for 1.0.4 release?

### ISSUE THREAD

**Issue by clydemcqueen** [Williangalvani/blueos-ugps-extension#4]
Any plans for a 1.0.4 release w/ the latest code?

**Comment by Williangalvani** [comment]
Hi clyde!
The extension was moved over to waterlinked: https://github.com/waterlinked/blueos-ugps-extension/
They will take care of future developments on it.
I'll update the readme and archive this repo

**Comment by clydemcqueen** [comment]
Hey Willian, thanks for the update.
